# envs/prod/infra/secrets.tf

resource "random_password" "grafana_admin_password" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "grafana_secret" {
  name        = "prod-grafana-admin-credentials"
  description = "Grafana admin user password (Automatically generated by Terraform)"
}

resource "aws_secretsmanager_secret_version" "grafana_secret_ver" {
  secret_id     = aws_secretsmanager_secret.grafana_secret.id
  secret_string = random_password.grafana_admin_password.result
}
